name: Sync mirrors
on:
  # schedule:
  #   # Run every 6 hours
  #   - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync-mirrors:
    name: Sync Jupiter/Holo Mirrors
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install evlaV and login
        run: |
          pip install -e .
          git config --global user.name "evlaV bot"
          git config --global user.email "evlav@bazzite.gg"
          
          echo "https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global credential.helper store
        
      - name: Sync Holo ISO Mirror
        run: |
          evlav holo \
            --readme=./readme-replace.md \
            --pull-remote="git+https://github.com/evlav" \
            --remote=https://github.com/evlav \
            --update-interval=1
